import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home-screen',
  templateUrl: './home-screen.component.html',
  styleUrls: ['./home-screen.component.scss']
})
export class HomeScreenComponent implements OnInit {


  dataSet = {
    mainData : [
    ],
    
    MTCBride8Veedu: [

{

        id: '83',
name: 'Hemeshwari',
dob: '13-11-1995',
Gender: 'Female',
Maritalstatus: 'Unmarried ',
educationdetail: 'BSC / BED / other',
education: 'Bsc MCA',
Height: '158',
Weight: '45',
BodyType: ' Average',
EatingHabits : 'Non Vegetarian',
native: 'Viruthunagar',
livingLocation: 'Viruthunagar',
veedu: '8',
Thali : 'Pottu',
Kulam : 'Not sure',
company: 'NA',
occupation: 'NA',
salary: 'NA',
class: 'Middle Class',
fathersname: 'Veraiaaya',
fathersOccupation: ' Business',
mothersname: 'Guru Bhakyam',
mothersOccupation: ' house wife',
siblings: '1',
siblingsmarriage         : '1',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Kadagam ',
natchathiram: 'Pusam',
Lagnam: 'Kaniya',
Expectation: 'Government Job',

},

{
        id: '84',
        name: 'Deepa lakshmi',
        dob: '25-12-1997',
        Gender: 'Female',
        Maritalstatus: 'Unmarried ',
        educationdetail: 'BSC / BED / other',
        education: 'Msc',
        Height: '5.5',
        Weight: 'Not sure',
        BodyType: ' Average',
        EatingHabits : 'Non Vegetarian',
        native: 'Kovai',
        livingLocation: 'Kovai',
        veedu: '8',
        Thali : 'Kombu',
        Kulam : 'Thavalaiyar',
        company: 'NA',
        occupation: 'NA',
        salary: 'NA',
        class: 'Middle Class',
        fathersname: 'Seniyappan',
        fathersOccupation: ' Business',
        mothersname: 'Raja lakshmi',
        mothersOccupation: ' house wife',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: 'Yes',
        dhosamdetails: 'Raghu kethu',
        rasi: 'THULAM',
        natchathiram: 'Visaga',
        Lagnam: 'Not sure',
        Expectation: 'Good job, education and with in tamil nadu',
        

},

      {
                id: '1',
name: 'HARSHITHA T',
dob: '12.09.1993',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'B.E',
Height: '5.4',
Weight: '57',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Hosur',
livingLocation: 'Hosur',
veedu: '8',
Thali : 'kombu ',
Kulam : 'Korahaiyar',
company: 'Cognizant Technology Solutions',
occupation: 'IT',
salary: '40000',
class: 'Middle Class',
fathersname: 'Thangavelu A',
fathersOccupation: 'Business',
mothersname: 'Meeradevi S',
mothersOccupation: 'Homemaker',
siblings: 'Brother studying B.E',
siblingsmarriage         : '1',
dhosam: 'No',
dhosamdetails: 'No',
rasi: 'Kadagam ',
natchathiram: 'Pusam',
Lagnam: 'Makaram',
Expectation: 'Age differnce 3 to 4 , Prefered Bangalore Groom',

                         


      },

     
      {
        id: '48',
        name: ' G.poornalakshmi',
        dob: ' 24.03.1997',
        Gender: ' female',
        Maritalstatus: 'Unmarried',
        educationdetail: 'BSC / BED / other',
        education: 'Bsc .Bed',
        Height: 'Not Received',
        Weight: 'Not Received',
        BodyType: 'Average',
        EatingHabits : 'Non Vegetarian',
        native: 'pallipalayam',
        livingLocation: ' Lakshmi nagar.Bhavani',
        veedu: '8',
        Thali : 'Kombu',
        Kulam : 'Makkadaiyar',
        company: 'Not Received',
        occupation: 'Teacher mother',
        salary: '6000',
        class: 'Middle Class',
        fathersname: 'Gunasekar',
        fathersOccupation: 'Examiner in court ',
        mothersname: ' G.Jayalakshmi',
        mothersOccupation: 'Home Maker',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: 'No',
        dhosamdetails: 'NA',
        rasi: 'Kani',
        natchathiram: 'Astam',
        Lagnam: 'Virchaga',
        Expectation: 'Vammaiyar,Vachiyavar, Mummudiyar',
        
      },

      {id: '74',
      name: ' H.Radha, ',
      dob: '  12.4.1987.',
      Gender: ' Female.',
      Maritalstatus: 'Unmarried ',
      educationdetail: 'BSC / BED / other',
      education: ' BCA',
      Height: ' 5.3 ft.',
      Weight: ' 54 kgs.',
      BodyType: ' Slim.',
      EatingHabits : 'Non Vegetarian',
      native: ' CHENNAI',
      livingLocation: ' Chennai',
      veedu: '8',
      Thali : ' Pottu',
      Kulam : 'Not Received',
      company: 'Not Received',
      occupation: 'Not Received',
      salary: 'Not Received',
      class: ' Middle class',
      fathersname: ' Harikrishnan',
      fathersOccupation: ' Govt.Transport (Rtrd)',
      mothersname: 'Not Received',
      mothersOccupation: ' house wife',
      siblings: '2',
      siblingsmarriage         : '1',
      dhosam: 'Yes',
      dhosamdetails: ' Ragu,sevvaai',
      rasi: 'Kanni',
      natchathiram: ' Uthiram ( 2 )',
      Lagnam: 'Not Received',
      Expectation: ' Generally',
      },

      {
        id: '68',
        name: ' Anitha S',
        dob: ' 01-Aug-1994',
        Gender: ' female',
        Maritalstatus: ' Unmarried',
        educationdetail: ' B.E',
        education: ' B.E EEE',
        Height: ' 5ft4in',
        Weight: '70',
        BodyType: ' Average',
        EatingHabits : ' Non Vegetarian',
        native: ' CHENNAI',
        livingLocation: ' Chennai',
        veedu: '8',
        Thali : ' Pottu',
        Kulam : ' sadhu chetty',
        company: ' Cognizant',
        occupation: ' Software Analyst',
        salary: ' 30K',
        class: ' Middle class',
        fathersname: ' Srinivasan S',
        fathersOccupation: ' Business',
        mothersname: ' Rajeswari S',
        mothersOccupation: ' House Wife ',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: ' No',
        dhosamdetails: 'NA',
        rasi: ' Rishabam',
        natchathiram: ' Krithikai',
        Lagnam: 'Not Recevied',
        Expectation: ' 16 veedu groom with good character.',
        
      },


      {      id: '43',
      name: 'VEERAVINODHINI P',
      dob: '18/08/1997',
      Gender: 'Female',
      Maritalstatus: 'Unmarried',
      educationdetail: 'Engineering /MBA',
      education: 'MCA, BL',
      Height: '5.3',
      Weight: '60',
      BodyType: 'Average',
      EatingHabits : 'Non Vegetarian',
      native: 'Kerala ',
      livingLocation: 'TIRUPUR',
      veedu: '8',
      Thali : 'Kombu',
      Kulam : 'Kavalaiyar (Irataiyar)(',
      company: 'Not Received',
      occupation: 'Not Received',
      salary: 'Not Received',
      class: 'Middle class ',
      fathersname: 'Palanisamy',
      fathersOccupation: 'Tailor ',
      mothersname: 'Usharani',
      mothersOccupation: 'Homemaker',
      siblings: '1',
      siblingsmarriage         : '0',
      dhosam: 'No',
      dhosamdetails: 'NA',
      rasi: 'Magaram',
      natchathiram: 'Avittam',
      Lagnam: 'Mithunam',
      Expectation: '28 yrs (Doctor ,BL,BE) , Excepting 100000 salary from groom',
      
      
      },


      {
                      id: '35',
name: 'P.Gayathri',
dob: '19/04/1993',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'B.tech(Biotechnology)',
Height: 'Not Received',
Weight: '5.6',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Tiruppur',
livingLocation: 'Chennai',
veedu: '8',
Thali : 'kombu ',
Kulam : 'Makkadaiyar',
company: 'private sector',
occupation: 'IT',
salary: 'Decent Income',
class: 'Upper Class',
fathersname: 'Paramasivam (Late)',
fathersOccupation: 'NA',
mothersname: 'Susila.P',
mothersOccupation: 'Home Maker',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'Yes',
dhosamdetails: 'Chevai (2)',
rasi: 'MEENAM',
natchathiram: 'uthiratathi',
Lagnam: 'Mithunam',
Expectation: 'Good Job , Family',


        
      },

      {        id: '36',
      name: 'J.PANDEESWARI',
      dob: '13.07.1992',
      Gender: 'Female',
      Maritalstatus: 'Unmarried',
      educationdetail: 'BSC / BED / other',
      education: 'Dip.Civil.engg',
      Height: 'Not Received',
      Weight: '5',
      BodyType: 'Slim',
      EatingHabits : 'Non Vegetarian',
      native: 'Pannapatti ',
      livingLocation: 'Madurai',
      veedu: '8',
      Thali : 'Kombu',
      Kulam : 'Kavalaiyar (Irataiyar)(',
      company: 'Private firm',
      occupation: 'Architect ',
      salary: '10000 P/m',
      class: 'Middle Class',
      fathersname: 'A.JEYAMURUGN',
      fathersOccupation: 'Own business',
      mothersname: ' J.SELVI',
      mothersOccupation: 'Home Maker',
      siblings: '2',
      siblingsmarriage         : '2',
      dhosam: 'No',
      dhosamdetails: 'NA',
      rasi: 'Thanusu',
      natchathiram: 'Moolam(4 patham)',
      Lagnam: 'Virchagam',
      Expectation: 'Good Job',
      
      

      },

      {

               id: '27',
name: 'Apsara S',
dob: '9.2.1991',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'BE',
Height: '155 CM',
Weight: '58',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Dindigul ',
livingLocation: 'Chennai',
veedu: '8',
Thali : 'Not Sure',
Kulam : 'Pillivangavar',
company: 'Not Received',
occupation: 'Not Received',
salary: 'Not Received',
class: 'Middle class ',
fathersname: 'Srinivasan N(late)',
fathersOccupation: 'NA',
mothersname: ' Jeyalakshmi S',
mothersOccupation: 'Home Maker',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'Not sure',
dhosamdetails: 'Not sure',
rasi: 'Veeruchaga',
natchathiram: 'Katai',
Lagnam: 'Not sure',
Expectation: 'IT Work',


      },

      {

                name: 'Vimala M',
        id: '28',
        dob: '08.10.1994',
        Gender:  'Female',
        Maritalstatus: 'Unmarried',
        dhosam:  'Not Received',
        fathersname: 'Not Received',
        fathersOccupation: 'Business',
         mothersname: 'Not Received',
        mothersOccupation: 'Home Maker',
        education: 'BBA, MBA, PGDHRM ',
        occupation: 'Not Received',
        company: 'HSBC Electronic Data Processing pvt Ltd , Bangalore',
        class: 'Not Received',
        salary: 'Not Received',
        veedu : '8',
        siblings : 'Not Received',
        native: 'Not Received',
        livingLocation: 'Not Received',

      },

      {id: '23',
      name: 'Hemalatha',
      dob: '17-10-1995',
      Gender: 'Female',
      Maritalstatus: 'Unmarried',
      educationdetail: 'Engineering /MBA',
      education: 'BE -ECE',
      Height: '5',
      Weight: '48',
      BodyType: 'Average',
      EatingHabits : 'Non Vegetarian',
      native: 'Theni',
      livingLocation: 'Theni',
      veedu: '8',
      Thali : 'Pottu',
      Kulam : 'Makkadaiyar',
      company: 'MNC- Core',
      occupation: 'Not Received',
      salary: '20000( Now Preparing government exam)',
      class: 'Middle Class',
      fathersname: 'K.Sundararaj',
      fathersOccupation: 'D.Sc Agricultural- Now (Farmer)',
      mothersname: 'S.Lakshmi',
      mothersOccupation: 'Home Maker',
      siblings: '2',
      siblingsmarriage         : '0',
      dhosam: 'No',
      dhosamdetails: 'NA',
      rasi: 'Kadagam ',
      natchathiram: 'Poosham ',
      Lagnam: 'Mesam',
      Expectation: 'Government Job',
      

        


      },

      {
              id: '25',
name: 'C. Parimaladevi ',
dob: '18.04.1989',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'BSC / BED / other',
education: 'B.sc.,M. SC.,  M. Phil',
Height: '160CM',
Weight: '50',
BodyType: 'Average',
EatingHabits : 'Vegetarian',
native: 'Udumalaipetti',
livingLocation: 'Erisinampatti,Udumalpet',
veedu: '8',
Thali : 'Kombu',
Kulam : 'Makkadaiyar',
company: 'Engineering College',
occupation: 'Assistant Professor ',
salary: '20000',
class: 'Middle Class',
fathersname: 'R. chokkalingam (late)',
fathersOccupation: 'NA',
mothersname: 'C. Subbulakshmi ',
mothersOccupation: 'Floor mills ',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'Yes',
dhosamdetails: 'RAGHU KEDHU DHOSAM',
rasi: 'Kani',
natchathiram: 'Uthradam',
Lagnam: 'Simam',
Expectation: 'Educated , good job',

        
      },

      {
              id: '21',
name: ' K.KAVITHA',
dob: '03.10.1994',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'B.Tech IT MBA.',
Height: '5.5',
Weight: '55',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Chennai',
livingLocation: 'Chennai',
veedu: '8',
Thali : 'Pottu',
Kulam : 'Not Received',
company: 'TCS ',
occupation: 'IT..software ',
salary: '40000',
class: 'Upper middle class ',
fathersname: 'S.KARUPPAN',
fathersOccupation: 'IT.professional ',
mothersname: 'K.Muthumari',
mothersOccupation: 'Home Maker',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'RAGHU KEDHU DHOSAM',
rasi: 'Simam',
natchathiram: 'Puram',
Lagnam: 'Meenam',
Expectation: 'Engineering , Settled , Good family, Chennai',

      },

     
      {
               id: '12',
name: ' H. Gnana priya ',
dob: '15/12/1996',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'BSC / BED / other',
education: 'B. Com',
Height: '5.5',
Weight: '57',
BodyType: 'Average',
EatingHabits : 'Vegetable',
native: 'Salem ',
livingLocation: 'Salem ',
veedu: '8',
Thali : 'Kombu',
Kulam : 'Not Received',
company: 'Not Received',
occupation: 'Not Received',
salary: 'Not Received',
class: 'Middle Class',
fathersname: 'm. HariKrishnan (late)',
fathersOccupation: 'NA',
mothersname: 'H. Rukumani',
mothersOccupation: 'business ',
siblings: '2',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Kumbam',
natchathiram: 'Avittam',
Lagnam: 'Not Received',
Expectation: 'Good family',


      },
      
    ],

MTCGroom8Veedu: [
      {
         name: 'R. Vigneshkumar',
        id: '2',
        dob: '09.03.1990',
        Gender:  'Male',
        Maritalstatus: 'Unmarried ',
        dhosam:  'Not Received',
        fathersname: 'Rajendran',
        fathersOccupation: 'Self employed',
         mothersname: 'Ms.  Maheswari',
        mothersOccupation: 'Self employed',
        education: 'M. B. A(logistics)',
        occupation: 'Materialsmanager',
        company: 'Auro lab ( Aravind eye hospitals  Madurai)',
        class: 'Middle',
        salary: '32000  pm',
        veedu : '8',
        siblings : 'No',
        native: 'B. K. Patty   THENI',
        livingLocation: 'Madurai.',

      },

      {
        id: '78',
        name: 'Manoj Kumar',
        dob: '28-08-1995',
        Gender: 'Male',
        Maritalstatus: 'Unmarried ',
        educationdetail: 'Engineering /MBA',
        education: 'BE (mech)',
        Height: '5.1',
        Weight: '65',
        BodyType: ' Average',
        EatingHabits : 'Non Vegetarian',
        native: 'Thiruvannamali',
        livingLocation: 'Thiruvannamali',
        veedu: '8',
        Thali : 'Pottu',
        Kulam : 'Pillivangavar',
        company: 'Herbam',
        occupation: 'Service Engineer',
        salary: '50000',
        class: ' Middle class',
        fathersname: 'Murthy',
        fathersOccupation: 'Business',
        mothersname: 'Tamil teacher',
        mothersOccupation: 'Government Teacher',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: 'No',
        dhosamdetails: 'NA',
        rasi: 'Simam',
        natchathiram: 'Magam',
        Lagnam: 'Kadamgam',
        Expectation: 'Good Education , good family and Working ',
        
      },

      {
        id: '76',
        name: 'Chandrajan',
        dob: '32817',
        Gender: 'Male',
        Maritalstatus: 'Unmarried ',
        educationdetail: 'Doctor',
        education: 'Doctor',
        Height: '6',
        Weight: '75',
        BodyType: ' Average',
        EatingHabits : 'Non Vegetarian',
        native: 'Coimbatore',
        livingLocation: 'Tambaram - chennai',
        veedu: '8',
        Thali : 'Pottu',
        Kulam : 'Thavalaiyar',
        company: 'ASCLM College ',
        occupation: 'Professor',
        salary: '30000',
        class: 'Upper middle class',
        fathersname: 'Raja',
        fathersOccupation: 'Real estate',
        mothersname: 'Thamarai',
        mothersOccupation: ' house wife',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: 'No',
        dhosamdetails: 'NA',
        rasi: 'Kumbam',
        natchathiram: 'Poratathi',
        Lagnam: 'Kani',
        Expectation: 'Good Education , good family and Good character',
        

      },

      {
        id: '72',
        name: 'Lakmana Prabu',
        dob: ' 08/Jan/1995',
        Gender: 'Male',
        Maritalstatus: 'Unmarried',
        educationdetail: 'Engineering /MBA',
        education: 'BE / MBA',
        Height: '5.2',
        Weight: '50',
        BodyType: 'Slim',
        EatingHabits : 'Non',
        native: 'Pollachi',
        livingLocation: 'Pollachi',
        veedu: '16',
        Thali : 'Kombu',
        Kulam : 'Mummudiyar',
        company: 'Bike show room (own)',
        occupation: 'Bike show room (own)',
        salary: 'NA',
        class: 'Upper Class',
        fathersname: 'Radhakrishnan',
        fathersOccupation: 'Bike, rice,lorry traders',
        mothersname: 'Thanalakshmi',
        mothersOccupation: 'Not Received',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: 'Yes',
        dhosamdetails: 'chevvai 8th house',
        rasi: 'MEENAM',
        natchathiram: 'Revathi',
        Lagnam: 'Not Received',
        Expectation: 'Well settled family ',
        
      },

      {
        id: '70',
        name: ' M.Hariharavignesh',
        dob: ' 03-Jan-1993',
        Gender: ' Male',
        Maritalstatus: ' Unmarried',
        educationdetail: 'Engineering /MBA',
        education: ' B.E',
        Height: '5ft6in',
        Weight: ' 70 KG',
        BodyType: 'Average',
        EatingHabits : ' Non vegetarian ',
        native: ' Erode',
        livingLocation: ' Erode',
        veedu: '8',
        Thali : 'Kombu',
        Kulam : 'Makkadaiyar',
        company: ' MNC, Bangalore',
        occupation: ' Data Scientist',
        salary: ' Data Scientist',
        class: ' Upper Middle',
        fathersname: ' S.Madeswaran',
        fathersOccupation: ' Business',
        mothersname: ' M.Mangayarkarasi',
        mothersOccupation: ' house wife',
        siblings: '1',
        siblingsmarriage         : '1',
        dhosam: ' No',
        dhosamdetails: 'NA',
        rasi: ' Measham',
        natchathiram: ' Bharani',
        Lagnam: ' Simmam',
        Expectation: 'Graduate,Good Looking & Well Settled family',
        
      },

      {id: '64',
      name: ' Muthalappan',
      dob: '18.Mar.93',
      Gender: ' Male',
      Maritalstatus: 'Unmarried ',
      educationdetail: 'M.Sc Agriculture',
      education: ' M.Sc Agri',
      Height: '5ft10in',
      Weight: '80 KG',
      BodyType: 'Athletic',
      EatingHabits : ' Example Non Vegetarian',
      native: ' virudhunagar',
      livingLocation: ' Maharajapuram',
      veedu: '8',
      Thali : 'Pottu',
      Kulam : 'Not Received',
      company: 'HDFC Bank',
      occupation: ' Deputy Manager',
      salary: '50000',
      class: ' Upper Middle',
      fathersname: 'Sundararajan.V ',
      fathersOccupation: ' Ex Army',
      mothersname: ' Alagammal',
      mothersOccupation: ' Home Maker',
      siblings: '2',
      siblingsmarriage         : '2',
      dhosam: 'No',
      dhosamdetails: 'NA',
      rasi: 'Magaram',
      natchathiram: ' Uthiradam',
      Lagnam: ' kadagam',
      Expectation: ' Banking and teaching professional',
      },

      {
        id: '60',
name: ' Arjun',
dob: '24.2.1995',
Gender: ' Male',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering',
education: 'B.E ',
Height: '5ft2in',
Weight: '50kg',
BodyType: 'Slim',
EatingHabits : 'Non Vegetarian',
native: 'Pollachi',
livingLocation: 'Pollachi',
veedu: '8',
Thali : 'Pottu',
Kulam : 'koragayar',
company: 'TCS Chennai',
occupation: 'Not Received',
salary: '40000',
class: 'Upper middle class',
fathersname: 'Not Received',
fathersOccupation: ' Business',
mothersname: 'Not Received',
mothersOccupation: 'Home Maker',
siblings: '1',
siblingsmarriage         : '1',
dhosam: 'Not Received',
dhosamdetails: 'Not Received',
rasi: 'Not received',
natchathiram: 'Not Received',
Lagnam: 'Not received',
Expectation: 'A degree hold ',

        
      },

      {
               id: '52',
name: ' GOPALAKRISHNAN P',
dob: '23/10/1990',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'MCA',
Height: '5.6',
Weight: '84',
BodyType: 'little Heavy',
EatingHabits : 'Non Vegetarian',
native: 'Kerala ',
livingLocation: 'Tiruppur',
veedu: '8',
Thali : 'Kombu',
Kulam : 'Kavalaiyar (Irataiyar)(',
company: 'Axis Bank ',
occupation: 'Banking',
salary: '35000',
class: 'Upper Middleclass',
fathersname: 'Palanisamy',
fathersOccupation: 'Dress maker',
mothersname: 'Usharani',
mothersOccupation: 'Home maker ',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'Chevvai  4th House',
dhosamdetails: '(blank)',
rasi: 'Vrichigam ',
natchathiram: 'Kettai / Jyesta ',
Lagnam: 'kumbam',
Expectation: 'Good Family and educated',

        
      },

      {
               id: '53',
name: 'S.Vishnu Bharath',
dob: '22.12.1987',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'BBM., MBA.,',
Height: '6.5',
Weight: '65',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Tirupur',
livingLocation: 'Palladam Road 1 km from old bus stand',
veedu: '8',
Thali : 'Kombu',
Kulam : 'Makkadaiyar',
company: 'Chemical Industry posting as South Indian Manager',
occupation: 'Non IT',
salary: '60000 + ',
class: 'Middle upper class',
fathersname: 'N.Sadhasivam',
fathersOccupation: 'Cotton business',
mothersname: 'S.Indrani',
mothersOccupation: 'Home Maker',
siblings: '1',
siblingsmarriage         : '1',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Thanusu',
natchathiram: 'Poraatam',
Lagnam: 'Not Received',
Expectation: 'Good Family & educated (Groom has Land)',

        
      },

      {
              id: '49',
name: ' ITHAYA KUMAR M',
dob: '6.11.1991',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'BSC / BED / other',
education: ' B.COM /M.COM',
Height: '173',
Weight: 'Not Received',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'THENI (KODANGIPATY)',
livingLocation: 'THENI (KODANGIPATY)',
veedu: '8',
Thali : 'Pottu',
Kulam : 'Thavalaiyar',
company: ' RAJSHREE BIOSOLITIONS PVT LTD',
occupation: 'CHIEF ACCOUNTANT/STORE MANAGER',
salary: '25000',
class: 'Middle class ',
fathersname: 'MANIKANDAN V',
fathersOccupation: 'BUISNESS',
mothersname: 'VEERALAKSHMI M',
mothersOccupation: 'Home Maker',
siblings: '2',
siblingsmarriage         : '1',
dhosam: 'Yes',
dhosamdetails: 'RAGHU KEDHU',
rasi: 'THULAM',
natchathiram: 'VISAKAM',
Lagnam: 'Risaba',
Expectation: 'Height , chennai and educated',


        
      },

      {

               id: '50',
name: 'Vinoth Kumar.K',
dob: '11.8.1985',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'M.COM,MBA',
Height: '5.11',
Weight: '68',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Near Devanur Puthur',
livingLocation: ' Near Devanur Puthur.',
veedu: '8',
Thali : 'Kombu',
Kulam : 'Thavalaiyar',
company: 'Annavasal Palani',
occupation: 'Manager at Hote',
salary: '25000',
class: 'Middle class ',
fathersname: 'Krishnasamy',
fathersOccupation: 'Coconut& Cotton Business',
mothersname: 'Saraswathi',
mothersOccupation: 'Home Maker',
siblings: '1',
siblingsmarriage         : '1',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Risabam',
natchathiram: 'Rohini',
Lagnam: 'Simma',
Expectation: 'No Exceptation (Groom has own house)',


      },
      {
                name: 'S ALAGARSAMY',
                id: '37',
                dob: '02.11.1996',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'Not Received',
                fathersname: 'T SELVARAJ',
                fathersOccupation: 'EXARMY',
                 mothersname: 'S JOTHI',
                mothersOccupation: 'NIL  ',
                education: 'BE',
                occupation: 'Business ',
                company: 'SRI SELVA JOTHI AGENCY',
                class: 'Middle Class',
                salary: '20000-25000',
                veedu : '8',
                siblings : 'Not Received',
                native: 'Theni',
                livingLocation: 'Theni',
        
      },

      {
                       name: 'B. Gokulnathan',
        id: '30',
        dob: '8.1.1993',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'No',
        fathersname: 'Balasubaramaniam',
        fathersOccupation: 'Business ',
         mothersname: 'vijaya',
        mothersOccupation: 'occupation ',
        education: 'BE',
        occupation: 'Engineer',
        company: 'Sonali extrusion pvt. Limited',
        class: 'Middle ',
        salary: '30000',
        veedu : '8',
        siblings : '1 sister (married) ',
        native: 'kottur',
        livingLocation: 'Coimbatore',

        
      },

      {
                name: 'Velmurugan',
                id: '31',
                dob: 'Age 40',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'No',
                fathersname: 'Palanisamy Chettiyar(Late)',
                fathersOccupation: 'NA',
                 mothersname: 'Kousalya',
                mothersOccupation: 'Home maker ',
                education: 'B.sc',
                occupation: 'Business ',
                company: 'Own Merchant',
                class: 'Middle/uppper ',
                salary: '50000',
                veedu : '8',
                siblings : 'No',
                native: 'Pollachi',
                livingLocation: 'Pollachi',
        
      },



      {
                name: 'Sivakumar.G',
                id: '29',
                dob: '24.1.1988',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'chevvai or sutha jathagam',
                fathersname: 'Gurunathan(late)',
                fathersOccupation: 'NA',
                 mothersname: 'Radha',
                mothersOccupation: 'Grocer',
                education: 'M.A., M.Phil., ',
                occupation: 'Journalist ',
                company: 'Daily newspaper',
                class: 'Middle class ',
                salary: '38000',
                veedu : '8',
                siblings : '1 Brother',
                native: 'Salem ',
                livingLocation: 'Neikkaarappatty',
        
      },

      {
                        name: 'S. ANGURAJ',
        id: '26',
        dob: '2.8.1989',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'Raghu Kadhu ',
        fathersname: 'Subramaniam ',
        fathersOccupation: 'Business',
         mothersname: 'Bhagayalakshmi',
        mothersOccupation: 'Home Maker',
        education: 'BE -EEE',
        occupation: 'Private sector Business ',
        company: 'private sector',
        class: 'Middle Class',
        salary: 'Not Received',
        veedu : '8',
        siblings : '1 sister -married',
        native: 'udumalpet',
        livingLocation: 'udumalpet',

        

      },

      {
                name: 'Janarthanan',
                id: '24',
                dob: '16/10/1991',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'Ragu Keethu ',
                fathersname: 'R.Thangaraj',
                fathersOccupation: 'Not Received',
                 mothersname: 'Dhanalakshmi ',
                mothersOccupation: 'Not Received',
                education: 'Diploma catering',
                occupation: 'Own Business',
                company: 'Own Business',
                class: 'Not Received',
                salary: '30000',
                veedu : '8',
                siblings : '1 Brother',
                native: 'Trichy ',
                livingLocation: 'Not Received',
        
      },

      {
                name: 'sanjeevan ',
        id: '17',
        dob: '10.05.1972',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'No',
        fathersname: 'Not Received',
        fathersOccupation: 'Not Received',
         mothersname: 'Not Received',
        mothersOccupation: 'Not Received',
        education: 'B sc., agricultural science',
        occupation: 'Sanjeevan agro service',
        company: 'Sanjeevan agro service',
        class: 'Not Received',
        salary: 'Not Received',
        veedu : '8',
        siblings : 'Not Received',
        native: 'Not Received',
        livingLocation: 'Not Received',

      },
      {               name: 'Kamlesh',
              id: '19',
              dob: '3.5.1977',
              Gender:  'Male',
              Maritalstatus: 'Not Received',
              dhosam:  'Not Received',
              fathersname: 'Not Received',
              fathersOccupation: 'Not Received',
               mothersname: 'Not Received',
              mothersOccupation: 'Not Received',
              education: 'M.tech(Business)',
              occupation: 'Not Received',
              company: 'Not Received',
              class: 'Not Received',
              salary: '50000(Rent)',
              veedu : '8',
              siblings : 'Not Received',
              native: 'Not Received',
              livingLocation: 'Not Received',
      
      },
      {
                name: 'Vignesh',
                id: '9',
                dob: '16.09.1991',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'Ragu Kethu',
                fathersname: 'Raja',
                fathersOccupation: 'Accounts in metal shop',
                 mothersname: 'Malarkodi',
                mothersOccupation: 'Home Maker',
                education: '12th',
                occupation: 'Album design ( own business )',
                company: 'Album design ( own business )',
                class: 'Middle Class',
                salary: '25000rs',
                veedu : '8',
                siblings : '1 elder brother married 2 younger brother',
                native: 'athappanpatti ( ottanchathram )',
                livingLocation: 'Coimbatore',
        

      },
     
     {
              name: 'Anandha Kumar',
              id: '11',
              dob: '18.04.1988',
              Gender:  'Male',
              Maritalstatus: 'Unmarried',
              dhosam:  'No',
              fathersname: 'Ramakrishnan.k',
              fathersOccupation: 'Flower ',
               mothersname: 'palaniammal',
              mothersOccupation: 'Home maker/occupation ',
              education: 'B.B.M',
              occupation: 'Business ',
              company: 'RP Digital Lights&Sounds& Decors Event management',
              class: 'Middle Class',
              salary: '60000',
              veedu : '8',
              siblings : 'one sister married',
              native: 'Theni',
              livingLocation: 'TIRUPUR',
      

     },

     {       id: '13',
     name: 'K GEETHAPRIYAN ',
     dob: '27-12-1979 ',
     Gender: 'Male',
     Maritalstatus: 'Unmarried',
     educationdetail: 'BSC / BED / other',
     education: 'Bsc',
     Height: '173',
     Weight: '63',
     BodyType: 'ATHLETIC ',
     EatingHabits : 'Non Vegetarian',
     native: 'Palakkad Kerala',
     livingLocation: 'Palakkad Kerala',
     veedu: '8',
     Thali : 'Kombu',
     Kulam : 'Thavalaiyar',
     company: 'GD Deals(Reclaimed Wood Business)',
     occupation: 'Business(Long Leave from Government Job)',
     salary: '100000',
     class: 'Middle Class',
     fathersname: 'K KRISHNASWAMY (RAJU)',
     fathersOccupation: 'Passed away',
     mothersname: 'INDRANI KRISHNASWAMY ',
     mothersOccupation: 'Home maker ',
     siblings: '2',
     siblingsmarriage         : '1',
     dhosam: 'Not Received',
     dhosamdetails: 'Not Received',
     rasi: 'MEENAM',
     natchathiram: 'REVATHY ',
     Lagnam: 'RISHABAM',
     Expectation: '(blank)',
     
},

{
                       name: 'R.Vignesh kumar',
                id: '16',
                dob: '9.3.1990',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'No',
                fathersname: 'K.Rajendran',
                fathersOccupation: 'Business',
                 mothersname: 'R.Maheswari',
                mothersOccupation: 'Home Maker',
                education: 'B.com CA MBA',
                occupation: 'Logistics aurolab (Aravind eye hospital) Madurai',
                company: 'Not Received',
                class: 'Middle Class',
                salary: '30000',
                veedu : '8',
                siblings : 'Not Received',
                native: 'BK.patti,Theni ',
                livingLocation: 'BK.patti,Theni ',
        

},
      
    ],
MTCBride16Veedu : [


        {

                id: '85',
name: 'Hemapriyanga',
dob: '10.10.1993',
Gender: 'Female',
Maritalstatus: 'Unmarried ',
educationdetail: 'BSC / BED / other',
education: 'MCA',
Height: '5.5',
Weight: '54',
BodyType: ' Average',
EatingHabits : 'Non Vegetarian',
native: 'Kovai',
livingLocation: 'Kovai',
veedu: '16',
Thali : 'Pottu',
Kulam : 'Naliviraiyavar',
company: 'NA',
occupation: 'NA',
salary: 'NA',
class: 'Middle Class',
fathersname: 'Rengasami',
fathersOccupation: 'Police retired',
mothersname: 'Amsaveni',
mothersOccupation: ' house wife',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Kadagam ',
natchathiram: 'Pusam',
Lagnam: 'Not sure',
Expectation: 'Good job, education and salary',


        },


        {
                id: '86',
                name: 'Gajalakshmi',
                dob: 'April -- 1982',
                Gender: 'Female',
                Maritalstatus: 'Unmarried ',
                educationdetail: 'BSC / BED / other',
                education: 'MA(Tamil & English)',
                Height: '5.5',
                Weight: 'Not sure',
                BodyType: ' Average',
                EatingHabits : 'Non Vegetarian',
                native: 'Viruthunagar',
                livingLocation: 'Chennai',
                veedu: '16',
                Thali : 'Pottu',
                Kulam : 'Not sure',
                company: 'NA',
                occupation: 'NA',
                salary: 'NA',
                class: 'Middle Class',
                fathersname: 'Subramani',
                fathersOccupation: 'Business',
                mothersname: 'Saguthala',
                mothersOccupation: ' house wife',
                siblings: '2',
                siblingsmarriage         : '1',
                dhosam: 'No',
                dhosamdetails: 'NA',
                rasi: 'Mithunam',
                natchathiram: 'Punarpusam',
                Lagnam: 'Not sure',
                Expectation: 'Good job, education and salary',
                

        },
      {

                   id: '18',
name: 'BAAVANA',
dob: '21/10/1995',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'B.com., MBA (Finance)',
Height: '5',
Weight: '55',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Chennai',
livingLocation: 'Chennai',
veedu: '16',
Thali : 'Kombu',
Kulam : 'Mummudiyar',
company: 'Accenture - Chennai',
occupation: 'Not Received',
salary: 'on request',
class: 'Upper middle class ',
fathersname: 'V N Karunakaran',
fathersOccupation: 'Business',
mothersname: 'Nirmala',
mothersOccupation: 'occupation ',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'Yes',
dhosamdetails: 'Kethu 2nd place and Raghu in 8th place',
rasi: 'Simham',
natchathiram: 'Uthitam 1st padam',
Lagnam: 'Meenam',
Expectation: 'Groom should be in chennai , clean habit, Educated.Good Job',

       
      },

      {

        id: '75',
name: 'Suganya',
dob: '34115',
Gender: 'Female',
Maritalstatus: 'Unmarried ',
educationdetail: 'BSC / BED / other',
education: 'Msc Maths',
Height: '5.6',
Weight: '56',
BodyType: ' Average',
EatingHabits : 'Non Vegetarian',
native: 'Pollachi',
livingLocation: 'Karur',
veedu: '16',
Thali : 'Kombu',
Kulam : 'Kappavar',
company: 'Business',
occupation: 'Mobile Shop',
salary: '40000',
class: 'Upper middle class',
fathersname: 'Nagaraj(late)',
fathersOccupation: 'NA',
mothersname: 'Velu mani',
mothersOccupation: ' house wife',
siblings: '1',
siblingsmarriage         : '1',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Kadagma',
natchathiram: 'Poosam',
Lagnam: 'Simam',
Expectation: 'Near Karur, Good education , business or good job,Settled',

      },

      {
        id: '69',
name: ' P VIJAYDEEPA',
dob: ' April-28-1992',
Gender: 'Female ',
Maritalstatus: 'Unmarried ',
educationdetail: 'BSC / BED / other',
education: 'Viscom(Loyola college),preparing for civil service',
Height: '5.4',
Weight: '50',
BodyType: 'Slim',
EatingHabits : 'Non Vegetarian',
native: 'Theni',
livingLocation: 'Pollachi',
veedu: '16',
Thali : ' Pottu ',
Kulam : 'Madhalaiyavar',
company: 'NA',
occupation: 'NA',
salary: 'NA',
class: 'Upper middle class',
fathersname: 'P R G PAULRAJ ',
fathersOccupation: ' DOCTOR',
mothersname: ' P POONGODI',
mothersOccupation: 'Doctor',
siblings: '2',
siblingsmarriage         : '1',
dhosam: 'Yes',
dhosamdetails: 'chevvai',
rasi: 'Kumbam',
natchathiram: 'pooratadhi',
Lagnam: 'kanni',
Expectation: 'well read decent educated family',

        
      },

{
        id: '71',
name: 'Sowmiya',
dob: ' 11/Dec/1997',
Gender: 'Female',
Maritalstatus: ' Unmarried',
educationdetail: 'Engineering /MBA',
education: 'BE(EEE)',
Height: '5.2',
Weight: '55',
BodyType: 'Avearge',
EatingHabits : ' Non vegetarian ',
native: 'Pollachi',
livingLocation: 'Pollachi',
veedu: '16',
Thali : 'Kombu',
Kulam : 'Kolavar',
company: 'CAP Gemini',
occupation: 'IT',
salary: '35000',
class: 'Middle',
fathersname: 'Maanikam',
fathersOccupation: 'TNSTC(retired)',
mothersname: 'illavarasi',
mothersOccupation: 'Not Received',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Mesam',
natchathiram: 'Barani',
Lagnam: 'Mesam',
Expectation: 'IT ,Bank & Governament professional & don’t want farmer',

},

      {
        id: '58',
name: 'Vijayalakshmi',
dob: '7.Nov.95',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'B.sc Agri / MBA',
Height: '158',
Weight: '55',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Pollachi',
livingLocation: 'Pollachi',
veedu: '16',
Thali : 'Kombu',
Kulam : 'kumbidiyar',
company: 'Not Received',
occupation: 'Argi officer',
salary: '50000',
class: 'Middle Class',
fathersname: 'Mugukesan',
fathersOccupation: 'Business',
mothersname: 'Surana latha',
mothersOccupation: 'Teacher',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'Not sure',
dhosamdetails: 'Not sure',
rasi: 'Mesa',
natchathiram: 'Bharani ',
Lagnam: 'Kani',
Expectation: 'Not much exceptation , Gov Job / IT Job',

      },

      {

               id: '34',
name: 'Harishma',
dob: '4.2.1996',
Gender: 'Female',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'B.Tech (IT)',
Height: '163',
Weight: '55',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Not Received',
livingLocation: 'Palani',
veedu: '16',
Thali : 'kombu ',
Kulam : 'Mummudiyar',
company: 'WIPRO',
occupation: 'IT',
salary: '40000',
class: 'Not Received',
fathersname: 'Mahalingam',
fathersOccupation: 'Not Received',
mothersname: 'Umamaheshwari',
mothersOccupation: 'Not Received',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Kadagam ',
natchathiram: 'Pusam',
Lagnam: 'Magaram',
Expectation: 'Good Job ,IT',


      },


      {        id: '20',
      name: 'P.M.ANITHA',
      dob: '06.03.1990',
      Gender: 'Female',
      Maritalstatus: 'Unmarried',
      educationdetail: 'Engineering /MBA',
      education: ' B.E',
      Height: '5.5',
      Weight: '55',
      BodyType: 'Average',
      EatingHabits : 'Non Vegetarian',
      native: 'Chennai',
      livingLocation: 'Chennai',
      veedu: '16',
      Thali : 'Pottu',
      Kulam : 'Chennaiyavar',
      company: 'HCL TECHNOLOGY',
      occupation: 'IT',
      salary: '60000',
      class: 'Upper class ',
      fathersname: 'P.G.MURALIKUMAR',
      fathersOccupation: 'Business',
      mothersname: 'P.M.LATHA',
      mothersOccupation: 'BUSINESS',
      siblings: '1',
      siblingsmarriage         : '0',
      dhosam: 'No',
      dhosamdetails: 'NA',
      rasi: 'Methunam',
      natchathiram: 'Pusam',
      Lagnam: 'Not Received',
      Expectation: 'Engineering , Settled , Good family',
      
      },
      
    ],
MTCGroom16Veedu: [
      {
               id: '3',
name: 'V.Karthik',
dob: '10.Jan.1989',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'B.tech',
Height: '5.8',
Weight: '60',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Thanjur',
livingLocation: 'Chennai',
veedu: '16',
Thali : 'kombu ',
Kulam : 'Tharishiyavar',
company: 'TCS',
occupation: 'IT',
salary: '50000',
class: 'Middle Class',
fathersname: 'Vadivel',
fathersOccupation: 'Late',
mothersname: 'Rani',
mothersOccupation: 'Home Maker',
siblings: '2',
siblingsmarriage         : '2',
dhosam: 'Not sure',
dhosamdetails: 'Not sure',
rasi: 'Magaram',
natchathiram: 'Avitam',
Lagnam: 'Magaram',
Expectation: 'Not Expectation.',



      },

      {id: '82',
      name: ' Venkatesh A',
      dob: ' 07.04.1988',
      Gender: 'Male',
      Maritalstatus: 'Unamarried',
      educationdetail: 'BSC / BED / other',
      education: ' BC',
      Height: '5.6',
      Weight: '100',
      BodyType: ' Heavy',
      EatingHabits : 'Non Vegetarian',
      native: ' Coimbatore',
      livingLocation: ' Coimbatore',
      veedu: '16',
      Thali : 'Pottu',
      Kulam : ' kolaiyavar',
      company: ' Expeditors, Coimbatore',
      occupation: ' Executive Manager',
      salary: ' 4.8l pa',
      class: ' Upper Middle',
      fathersname: ' Anandan V N(late)',
      fathersOccupation: ' Business',
      mothersname: 'Meenakumari C S',
      mothersOccupation: ' AEE(TNHB) Retired',
      siblings: '1',
      siblingsmarriage         : '1',
      dhosam: ' No',
      dhosamdetails: 'NA',
      rasi: ' Vrishigam',
      natchathiram: ' Kettai',
      Lagnam: ' Rishabam',
      Expectation: ' Educated bride with family values',
      },

      {
        id: '81',
        name: 'Vijakumar',
        dob: '28-01-1983',
        Gender: 'Male',
        Maritalstatus: 'Unmarried ',
        educationdetail: 'BSC / BED / other',
        education: 'B.com',
        Height: '5.4',
        Weight: '50',
        BodyType: ' Average',
        EatingHabits : 'Non Vegetarian',
        native: 'Thrichy',
        livingLocation: 'Thrichy',
        veedu: '16',
        Thali : 'Kombu',
        Kulam : 'Vachiyavar',
        company: 'Business (Travels)',
        occupation: 'Business (Travels)',
        salary: 'Business (Travels)',
        class: 'Upper middle class',
        fathersname: 'Natarajan(Late)',
        fathersOccupation: 'NA',
        mothersname: 'vijaya',
        mothersOccupation: ' house wife',
        siblings: '1',
        siblingsmarriage         : '1',
        dhosam: 'No',
        dhosamdetails: 'NA',
        rasi: 'Kadagam ',
        natchathiram: 'Puram',
        Lagnam: 'Not sure',
        Expectation: 'Not Exception',
        
      },

      {
        id: '77',
        name: 'Arun Raj',
        dob: '13-09-1989',
        Gender: 'Male',
        Maritalstatus: 'Unmarried ',
        educationdetail: 'BSC / BED / other',
        education: 'B.com,M.com , M phil',
        Height: '5.6',
        Weight: '65',
        BodyType: ' Average',
        EatingHabits : 'Non Vegetarian',
        native: 'salem',
        livingLocation: 'salem',
        veedu: '16',
        Thali : 'Kombu',
        Kulam : 'SengaKuruvar',
        company: 'College',
        occupation: 'Professor',
        salary: '20000',
        class: ' Middle class',
        fathersname: 'Soma sundaram',
        fathersOccupation: 'professional Courier',
        mothersname: 'Radha',
        mothersOccupation: ' house wife',
        siblings: '1',
        siblingsmarriage         : '1',
        dhosam: 'No',
        dhosamdetails: 'NA',
        rasi: 'Magaram',
        natchathiram: 'Avitam ',
        Lagnam: 'Kani',
        Expectation: 'Good Family and Good Family(Groom has own Land)',
        
      },

      {
        id: '65',
        name: ' D ASHWTH PANDI',
        dob: ' 14.10.1994',
        Gender: ' Male',
        Maritalstatus: 'Unmarried',
        educationdetail: 'Engineering /MBA',
        education: 'B.E. CS',
        Height: '5 FT 11 INCH',
        Weight: ' 130KG',
        BodyType: ' Heavy',
        EatingHabits : ' Non Vegetarian',
        native: ' CHENNAI',
        livingLocation: 'TIRUPUR',
        veedu: '16',
        Thali : ' Pottu',
        Kulam : 'NALIVILIYAR',
        company: 'Not Received',
        occupation: ' AGENT',
        salary: '80000',
        class: 'Upper Middle',
        fathersname: ' T DURAI PANDI',
        fathersOccupation: ' Business',
        mothersname: ' D SELVI',
        mothersOccupation: ' house wife',
        siblings: '1',
        siblingsmarriage         : '1',
        dhosam: 'No',
        dhosamdetails: 'NALIVILIYAR',
        rasi: ' MAGARAM',
        natchathiram: ' AVITTAM',
        Lagnam: ' KUMBAM',
        Expectation: ' EDUCATED AND GOOD FAMILY',
        
      },

      {
        id: '73',
        name: 'Naveen Kumar',
        dob: '20.Apr.1992',
        Gender: 'Male',
        Maritalstatus: 'Unmarried ',
        educationdetail: 'Engineering /MBA',
        education: ' B.E,MBA',
        Height: '5ft7in',
        Weight: '80 KG',
        BodyType: ' Average',
        EatingHabits : 'Non Vegetarian',
        native: ' Karaikudi',
        livingLocation: ' Chennai',
        veedu: '16',
        Thali : 'Kombu',
        Kulam : 'Kothavangavar',
        company: ' Temenos',
        occupation: ' Specialist',
        salary: ' 80 K',
        class: ' Middle class',
        fathersname: ' Panidaraj',
        fathersOccupation: ' Nil',
        mothersname: ' Gunasundari',
        mothersOccupation: ' house wife',
        siblings: '2',
        siblingsmarriage         : '2',
        dhosam: 'No',
        dhosamdetails: 'Not Received',
        rasi: ' Viruchikam',
        natchathiram: ' Anusham',
        Lagnam: ' Simam',
        Expectation: '8 veedu kombu thali bride',
        
      },

      {
        id: '66',
        name: ' Saravanan.N',
        dob: '  21-Feb-1989',
        Gender: ' Male',
        Maritalstatus: '  Unmarried',
        educationdetail: '  Arts science',
        education: ' BCOM(CA),PGDCA',
        Height: ' 5ft 72in',
        Weight: '70',
        BodyType: ' Average',
        EatingHabits : ' Vegetarian/Non ',
        native: ' Coimbatore',
        livingLocation: ' Sundakamuthur',
        veedu: '16',
        Thali : ' Pottu',
        Kulam : ' Vajavar',
        company: ' Jayachandran industrys Pvt Ltd',
        occupation: ' purchse & stores',
        salary: '30000',
        class: ' Middle',
        fathersname: ' Nataraj.R',
        fathersOccupation: ' Fruit stall',
        mothersname: ' Manimegali ',
        mothersOccupation: ' Hous wife',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: ' No',
        dhosamdetails: ' parikara sevai',
        rasi: ' sima rasi',
        natchathiram: ' puram',
        Lagnam: ' resabam',
        Expectation: 'good girl & good family',
        
      },
{

        id: '67',
name: ' P.Balasubramanian',
dob: ' 19-11-89',
Gender: ' Male',
Maritalstatus: ' Unmarried ',
educationdetail: ' Engineering                   ',
education: ' BE Mech',
Height: '5 ft 5inch',
Weight: ' 75 kgs',
BodyType: ' ',
EatingHabits : '  Non Vegetarian',
native: ' Pollachi',
livingLocation: ' Pollachi',
veedu: '16',
Thali : ' Pottu',
Kulam : ' Kenithiyar',
company: ' VSB Engg college',
occupation: ' instructor',
salary: '18000',
class: ' Middle class',
fathersname: ' A. Paramasivam',
fathersOccupation: ' labour',
mothersname: ' P.Nanjammal',
mothersOccupation: ' house wife',
siblings: '1',
siblingsmarriage         : '1',
dhosam: ' No',
dhosamdetails: ' No',
rasi: ' Kadakam',
natchathiram: ' Ayilyam',
Lagnam: ' Rishapam',
Expectation: ' 8 veedu bride',

},
      {

        id: '62',
name: ' Srinivasan M',
dob: ' 15-dec-1988',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'BSC / BED / other',
education: ' BBM',
Height: '5.6',
Weight: '80',
BodyType: ' Average',
EatingHabits : 'Not Received',
native: ' Trichy',
livingLocation: ' Bangalore',
veedu: '16',
Thali : 'Not Received',
Kulam : 'Not Received',
company: 'Jana small finance bank',
occupation: ' Credit manager',
salary: ' 35k',
class: ' Middle',
fathersname: 'Marudhai (late)',
fathersOccupation: 'NA',
mothersname: ' Sumathi',
mothersOccupation: ' Homemaker',
siblings: '4',
siblingsmarriage         : '4',
dhosam: ' No',
dhosamdetails: 'No',
rasi: ' Kumbam',
natchathiram: ' sathabhisha',
Lagnam: ' Thulam',
Expectation: ' Thulam',

      },

      {
        id: '63',
        name: ' V.Mohan Kumar',
        dob: ' 11-Nov-1990',
        Gender: ' Male',
        Maritalstatus: 'Unmarried',
        educationdetail: 'Engineering /MBA',
        education: ' Btech ',
        Height: '5.9',
        Weight: ' 98kg',
        BodyType: ' Heavy',
        EatingHabits : ' Non Vegetarian',
        native: ' Mettupalayam, Coimbatore',
        livingLocation: 'Mettupalayam, Coimbatore',
        veedu: '16',
        Thali : 'Kombu',
        Kulam : ' Tharisiyavar',
        company: 'WIPRO',
        occupation: ' Lead',
        salary: ' 75k  PM',
        class: ' Middle',
        fathersname: ' K.Varatharajan',
        fathersOccupation: ' late',
        mothersname: ' V.Chinthamani',
        mothersOccupation: ' business ',
        siblings: '1',
        siblingsmarriage         : '0',
        dhosam: ' No',
        dhosamdetails: 'NA',
        rasi: ' Simam',
        natchathiram: ' Pooram',
        Lagnam: ' Rishabam',
        Expectation: ' Educated',
        
      },

      {        name: 'Ramakrishnaprabu',
              id: '42',
              dob: '4.10.1984',
              Gender:  'Male',
              Maritalstatus: 'Unmarried',
              dhosam:  'No',
              fathersname: 'Hanumanthan',
              fathersOccupation: 'Retd Postmaster',
               mothersname: 'Angammal- Homemaker',
              mothersOccupation: 'Homemaker',
              education: 'B.sc ... Bed',
              occupation: 'Merchandiser',
              company: 'SCM',
              class: 'Middle class ',
              salary: '25000',
              veedu : '16',
              siblings : '2 Elder sister ( Married & well settled) ',
              native: 'Nilakottai',
              livingLocation: 'TIRUPUR',
              rasi:  'Maharam',
             natchathiram: 'Tiruvonam',
      },

      {id: '59',
      name: 'S.Rajakumar',
      dob: ' 29.12.1985',
      Gender: ' Male',
      Maritalstatus: '  Unmarried ',
      educationdetail: ' MBA',
      education: ' MBA',
      Height: '5ft6in',
      Weight: '60KG',
      BodyType: ' Slim',
      EatingHabits : 'Non Vegetarian',
      native: ' Coimbatore',
      livingLocation: ' Coimbatore',
      veedu: '16',
      Thali : 'Pottu',
      Kulam : 'Not Received',
      company: 'Not Received',
      occupation: ' Business Manager',
      salary: '45000',
      class: 'Upper middle class',
      fathersname: ' B.Sivaji',
      fathersOccupation: ' Business',
      mothersname: ' S.Nagamanickam',
      mothersOccupation: ' Home Maker',
      siblings: '1',
      siblingsmarriage         : ' Yes',
      dhosam: 'Yes ',
      dhosamdetails: 'Not Received',
      rasi: ' katagam',
      natchathiram: ' punarpoosam',
      Lagnam: '0',
      Expectation: '0',
      },

      {
                name: 'C Murugan',
                id: '55',
                dob: '20.04.76',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'No',
                fathersname: 'cinnusamy(late)',
                fathersOccupation: 'NA',
                 mothersname: 'c deivanayagi',
                mothersOccupation: 'Not Received',
                education: '10th',
                occupation: 'Labour',
                company: 'Nil',
                class: 'Middle class ',
                salary: '15000',
                veedu : '16',
                siblings : '4',
                native: 'devanurpudur ',
                livingLocation: 'Pollachi',
                rasi:  'Not received',
               natchathiram: 'Not Received',
        
      },

     

      {
                name: 'P.Karthik',
                id: '54',
                dob: '13/02/1991',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'No',
                fathersname: 'Palani(late)',
                fathersOccupation: 'NA',
                 mothersname: 'Ambiga',
                mothersOccupation: 'Home Maker',
                education: 'BE',
                occupation: 'Project Manager',
                company: 'Coir All Equipments,Villankurichi,Coimbatore ',
                class: 'Middle Class',
                salary: '30000',
                veedu : '16',
                siblings : '1 Younger Brother ',
                native: 'Uthangarai (Krishnagiri)',
                livingLocation: 'Uthangarai',
                rasi:  'Magaram',
               natchathiram: 'Thiruvonam -2',
        
      },


      {    
        id: '51',
        name: 'BharathKrishnan',
        dob: '11.08.1992',
        Gender: 'Male',
        Maritalstatus: 'Unmarried',
        educationdetail: '(blank)',
        education: 'B.Tech (IT), MS (CyberSecurity)',
        Height: '(blank)',
        Weight: '(blank)',
        BodyType: '(blank)',
        EatingHabits : '(blank)',
        native: 'Chennai',
        livingLocation: 'Chennai',
        veedu: '16',
        Thali : '(blank)',
        Kulam : '(blank)',
        company: 'EY',
        occupation: 'IT Consultant - Risk Advisory',
        salary: '12L ctc',
        class: 'Middle class ',
        fathersname: 'Radhakrishnan (late)',
        fathersOccupation: 'Accountant',
        mothersname: 'Gomathi',
        mothersOccupation: 'Home maker ',
        siblings: 'One brother(2nd Twin)',
        siblingsmarriage         : '(blank)',
        dhosam: 'Chevai- 1st house && Raghu- 8th house ketu in 2nd house',
        dhosamdetails: '(blank)',
        rasi: 'Dhansu',
        natchathiram: 'Pooradam -4 , Rishaba Lagnam',
        Lagnam: '(blank)',
        Expectation: '(blank)',
        
      },

{
                name: 'M.karthikeyan',
        id: '44',
        dob: '21.05.1993',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'Ragu Kethu',
        fathersname: ' A.murugesan',
        fathersOccupation: 'powerloom',
         mothersname: 'A.mageshewari',
        mothersOccupation: 'Home Maker',
        education: 'BE',
        occupation: 'sakthi auto components',
        company: 'employee',
        class: 'Middle class ',
        salary: '18000',
        veedu : '16',
        siblings : '1 sister (married)',
        native: 'Komarapalayam',
        livingLocation: 'Komarapalayam (Namakkal)',
        rasi:  'rishapam',
       natchathiram: 'kiruthikai',

},

{
                id: '45',
name: 'Karthick .p ',
dob: '10.7.1990',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineering /MBA',
education: 'BE civil ',
Height: '(blank)',
Weight: '(blank)',
BodyType: '(blank)',
EatingHabits : '(blank)',
native: 'servaikaranpatti ',
livingLocation: 'Dibba Fujairah uae',
veedu: '16',
Thali : '(blank)',
Kulam : '(blank)',
company: 'Majesty for gen construction and transport LLC ,DIBBA,Fujairah , uae ',
occupation: 'Senior engineer ',
salary: '1.25 lakhs per month',
class: 'Middle class ',
fathersname: 'Perumal ',
fathersOccupation: 'Cotton business ',
mothersname: 'Logambal ',
mothersOccupation: 'Home Maker',
siblings: '2 younger brothers ',
siblingsmarriage         : '(blank)',
dhosam: 'No',
dhosamdetails: '(blank)',
rasi: 'makram ',
natchathiram: 'Avittam',
Lagnam: '(blank)',
Expectation: '(blank)',


},

{       
        id: '46',
name: 'M.Bharath Kumar',
dob: '28-06-1991',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'BSC / BED / other',
education: 'M.Com',
Height: '6',
Weight: '72',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'chengalpattu',
livingLocation: 'chengalpattu',
veedu: '8',
Thali : 'Pottu',
Kulam : 'Not Received',
company: 'Private',
occupation: 'Bank Deputy Manager',
salary: '33000',
class: 'Middle class ',
fathersname: 'P Murugan',
fathersOccupation: 'Retired Police SI',
mothersname: 'M Jaya Bharathi',
mothersOccupation: 'Home Maker',
siblings: '2',
siblingsmarriage         : '2',
dhosam: 'Yes',
dhosamdetails: 'Ragu kethu',
rasi: 'Dhanusu',
natchathiram: 'Poraatam 3 patham',
Lagnam: 'Medunam',
Expectation: 'Height , color and educated',

},

{
                name: 'D. Vinodkanna ',
        id: '47',
        dob: '03.06.1992',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'Not Received',
        fathersname: 'Dhanashekherapandian ',
        fathersOccupation: 'Medical laboratory Technician( own diagnostic centre)',
         mothersname: 'Ms. Jamunarani',
        mothersOccupation: 'Home Maker',
        education: 'B. E( ECE)',
        occupation: 'Not Received',
        company: 'Plintron global solutions( Lyca)',
        class: 'Middle class ',
        salary: ' 50000 pm',
        veedu : '16',
        siblings : 'No',
        native: 'Periyakulam. Theni',
        livingLocation: 'Periyakulam',
        rasi:  'Not received',
       natchathiram: 'Not Received',

},

      {

                name: 'B. K. Anand kumar',
        id: '41',
        dob: '20/07/1986',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'Sutha jadhagam',
        fathersname: 'K.B.Karunanithi',
        fathersOccupation: 'Business',
         mothersname: 'S.K.Dravidaselvi',
        mothersOccupation: 'Home Maker',
        education: 'D.F.Tech in cinematography',
        occupation: 'Cinematographer n Director',
        company: 'Cine industry',
        class: 'Middle class ',
        salary: '10 - 15lakhs per annum',
        veedu : '16',
        siblings : 'Brother- K.Vivek Raju B.E., - Film maker. Sister-K.Swarnalega MBBS ',
        native: 'Coimbatore',
        livingLocation: 'kovundampalayam',
        rasi:  'Dhanushu ',
       natchathiram: 'pooradam 3 paadham',

      },
{
                      name: 'K Selvavinayagam',
        id: '38',
        dob: '25.06.1993',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'No',
        fathersname: 'M.krishnara',
        fathersOccupation: 'Rathi silk work',
         mothersname: 'Powaneshwari',
        mothersOccupation: 'Home Maker',
        education: '12th',
        occupation: 'Horlikes company',
        company: 'Horlikes company',
        class: 'Middle Class',
        salary: '18000',
        veedu : '16',
        siblings : '1 brother - 1 sister married',
        native: 'salem',
        livingLocation: 'salem',
        rasi:  'Simam',
       natchathiram: 'Pooram',


},

{

               id: '39',
name: 'P. Gopalakrishnan',
dob: '31.08.1989',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'BSC / BED / other',
education: 'D.M.E.',
Height: '5.6',
Weight: '60',
BodyType: 'Average',
EatingHabits : 'Non Vegetarian',
native: 'Thirukkazhukundram',
livingLocation: 'Thirukkazhukundram, Chengalpattu district',
veedu: '16',
Thali : 'Pottu',
Kulam : 'Not sure',
company: 'Govt. Employee, Town Panchayat Office',
occupation: 'Govt. Employee, Town Panchayat Office',
salary: '23000',
class: 'Middle Class',
fathersname: 'Perumal',
fathersOccupation: 'Painter',
mothersname: 'Nirmala',
mothersOccupation: 'Retired govt employee',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Simam',
natchathiram: 'Maga',
Lagnam: 'Simam',
Expectation: 'Educated (any degree)',


},

{

                name: 'Madhiyan',
        id: '40',
        dob: '02.06.1990',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'No',
        fathersname: 'B.J Gopal',
        fathersOccupation: 'Business and MGR Nagar Voor Thalaivar',
         mothersname: 'B.G Savithiri',
        mothersOccupation: 'Home Maker',
        education: 'SSLC',
        occupation: 'textile business',
        company: 'textile business',
        class: 'Middle Class',
        salary: '50000 to 100000',
        veedu : '16',
        siblings : '1 brother - 1 sister married',
        native: 'bargur Krishnagiri district',
        livingLocation: 'bargur Krishnagiri district',
        rasi:  'Kanni',
       natchathiram: 'Not Received',

},

      {
              id: '33',
name: 'Kathiresan J',
dob: '22.8.1984',
Gender: 'Male',
Maritalstatus: 'Unmarried',
educationdetail: 'Engineer ',
education: ' BE',
Height: '5”10',
Weight: '73',
BodyType: 'Average',
EatingHabits : 'Vegetarian',
native: 'Pollachi',
livingLocation: 'Udumalaipettai ',
veedu: '16',
Thali : 'Kombu',
Kulam : ' Mummudiyar',
company: 'Tata communication',
occupation: ' Assistant Manager',
salary: ' 9 Lak Per Annum',
class: 'Middle ',
fathersname: ' Jayaprakash ',
fathersOccupation: ' Farmer ',
mothersname: ' Kanniammal',
mothersOccupation: ' Retried (sathunavu amaipalar)',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'No',
rasi: ' Mithunam',
natchathiram: ' Thiruvathirai ',
Lagnam: ' Kumbha ',
Expectation: ' NO',


        
      },

      {
        id: '61',
name: ' Lakshmiraj J',
dob: ' 20.Aug.1982',
Gender: ' Male',
Maritalstatus: 'Unmarried ',
educationdetail: 'Arts Science ',
education: ' MCA',
Height: '5”15',
Weight: '65',
BodyType: 'Average ',
EatingHabits : 'Vegetarian ',
native: 'Pollachi ',
livingLocation: ' Udumalaipettai ',
veedu: '16',
Thali : 'Kombu',
Kulam : ' Mummudiyar',
company: 'Not Received',
occupation: ' Lead',
salary: ' 150000 PM',
class: 'Middle',
fathersname: ' Jayaprakash ',
fathersOccupation: ' Farmer',
mothersname: ' Kanniammalal',
mothersOccupation: ' Retried (sathunavu amaipalar)',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'Yes',
dhosamdetails: ' Raghu / Kethu',
rasi: ' Simha ',
natchathiram: ' Pooram ',
Lagnam: ' Mithunam',
Expectation: 'NO',

        
      },

      {
                        name: 'Kamaraj',
        id: '10',
        dob: '20-11-90',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'No',
        fathersname: 'M.Thiyagarajam',
        fathersOccupation: 'Retired',
         mothersname: 'T.Jothi',
        mothersOccupation: 'Home Maker',
        education: 'BE',
        occupation: 'Design Estimator - Cochin',
        company: 'IT',
        class: 'Middle Class',
        salary: '40000',
        veedu : '16',
        siblings : '1 sister -married && 1 Brother - Working in private sector',
        native: 'Pudukkottai',
        livingLocation: 'Cochin',
        rasi:  'Danush',
       natchathiram: 'Moolam',

      },
{
                name: 'Devendran',
                id: '22',
                dob: '27.5.1991',
                Gender:  'Male',
                Maritalstatus: 'Unmarried',
                dhosam:  'Ragu gethu dosam',
                fathersname: 'Gangadurai',
                fathersOccupation: 'Mechanic ',
                 mothersname: 'Rathina',
                mothersOccupation: 'Home Maker',
                education: '12th std',
                occupation: 'Agent in RTO office',
                company: 'Agent in RTO office',
                class: 'Middle',
                salary: '40000',
                veedu : '16',
                siblings : '1',
                native: 'Pollachi',
                livingLocation: 'Coimbatore',
        

},

      {
                name: 'K.Kalidhas',
        id: '4',
        dob: '28.06 1994',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'Not Received',
        fathersname: 'K.Kandasamy(Late)',
        fathersOccupation: 'NA',
         mothersname: 'K.Ayyammal',
        mothersOccupation: 'Home Maker',
        education: 'BE',
        occupation: 'Not Received',
        company: 'HCL Technologies Ltd , chennai',
        class: 'MIDDLE CLASS',
        salary: '40000',
        veedu : '16',
        siblings : '1 younger brother',
        native: 'Pollachi',
        livingLocation: 'Pollachi',

        

      },
      {
                name: 'logu j.m',
        id: '5',
        dob: '19-06-1990',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'Not Received',
        fathersname: 'murali .a',
        fathersOccupation: 'Business (Bakery consultancy)',
         mothersname: 'jayanthi.m',
        mothersOccupation: 'Home Maker',
        education: 'B.sc hotel managment ',
        occupation: 'Business (mens wear shop)',
        company: 'Vee fashion,5roads, salem',
        class: 'Upper middle class ',
        salary: '50-60k per month ',
        veedu : '16',
        siblings : '1 elder brother(married)and 1 younger sister(engaged)',
        native: 'salem',
        livingLocation: 'salem',


      },
      {        name: 'R.Gowtham',
              id: '6',
              dob: '01.03.1996',
              Gender:  'Male',
              Maritalstatus: 'Unmarried',
              dhosam:  'Not Received',
              fathersname: 'T.Ramakrishnan',
              fathersOccupation: 'Business',
               mothersname: 'R.Sumathi',
              mothersOccupation: 'Home Maker',
              education: 'D.EEE',
              occupation: 'Business ',
              company: 'Sri Sakthi Foods',
              class: 'Middle Class',
              salary: '30, 000-40, 000',
              veedu : '16',
              siblings : '1 Elder Sister Married',
              native: 'Pollachi Kottur',
              livingLocation: 'Palladam Tiruppur',
      

        

      },
      {
                name: 'VIGNESH KUMAR',
        id: '7',
        dob: '24/04/1991',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'RAGHU KETHU',
        fathersname: 'P.MURUGANATHAM',
        fathersOccupation: 'TRAVELS',
         mothersname: 'REVATHI',
        mothersOccupation: 'BUSSINES',
        education: 'BE. EEE',
        occupation: 'ENGINEERING',
        company: 'MALAYSIA',
        class: 'MIDDLE CLASS',
        salary: '75000',
        veedu : '16',
        siblings : '1 younger brother',
        native: 'Pollachi',
        livingLocation: 'KUALA LUMPUR, MALAYSIA',

        

      },
      {
                       name: 'Harinarendraprasath',
        id: '8',
        dob: '12.10.1994',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'No',
        fathersname: 'Sivalingam',
        fathersOccupation: 'TIIC govt retired',
         mothersname: 'Sabareeswari',
        mothersOccupation: 'Home Maker',
        education: 'BE',
        occupation: 'IT',
        company: 'Cognizant Technology Solutions,CBE',
        class: 'Upper Class',
        salary: '45000',
        veedu : '16',
        siblings : 'elder sister- Married',
        native: 'Vettaikkaranpudur, Pollachi',
        livingLocation: 'Vettaikkaranpudur',



      },

      {
                         name: 'vivek. J',
        id: '14',
        dob: '9.6.1991',
        Gender:  'Male',
        Maritalstatus: 'Unmarried',
        dhosam:  'Not Received',
        fathersname: 'JAISANKAR. T',
        fathersOccupation: 'bussiness',
         mothersname: 'kalanidhi. J',
        mothersOccupation: 'house wife',
        education: ' B.E',
        occupation: 'IT',
        company: 'Innopal',
        class: 'Middle Class',
        salary: 'yearly 5L',
        veedu : '16',
        siblings : 'one brother ',
        native: 'Chennai',
        livingLocation: 'Chennai',
        rasi:  'maesham ',
       natchathiram: 'Aswini',



      },
      
    ],
MTC16VeeduDoctor: [
      {
        

      },
      
    ],
MTC8VeeduDoctor: [
      {
        id: '56',
        name: 'P.Gokulapriya',
        dob: '12.1.1997',
        Gender: 'Female',
        Maritalstatus: 'Unmarried',
        educationdetail: 'Doctor',
        education: 'MBBS',
        Height: '(blank)',
        Weight: '(blank)',
        BodyType: '(blank)',
        EatingHabits : '(blank)',
        native: 'Periyampatti(Dharmapuri)',
        livingLocation: 'Periyampatti',
        veedu: '8',
        Thali : '(blank)',
        Kulam : '(blank)',
        company: 'MBBS ,Davao Medical,Phillipines ',
        occupation: 'Not Received',
        salary: '15000',
        class: 'Middle class ',
        fathersname: 'PanneerSelvam',
        fathersOccupation: 'MedicalShop',
        mothersname: 'Selvi',
        mothersOccupation: 'Village Nurse',
        siblings: '1 Younger Brother ',
        siblingsmarriage         : '(blank)',
        dhosam: 'No',
        dhosamdetails: '(blank)',
        rasi: 'Not received',
        natchathiram: 'Not Received',
        Lagnam: 'Not received',
        Expectation: '16 veedu MBBS Manamagan thevai',
        
        

      },
      
{
        id: '79',
name: 'Keerthana',
dob: '16-02-1999',
Gender: 'Female',
Maritalstatus: 'Unmarried ',
educationdetail: 'Doctor',
education: 'BDS',
Height: '5.5',
Weight: '55',
BodyType: ' Average',
EatingHabits : 'Non Vegetarian',
native: 'Thiruvannamali',
livingLocation: 'Thiruvannamali',
veedu: '8',
Thali : 'Pottu',
Kulam : 'Pillivangavar',
company: 'Not Received',
occupation: 'Not Received',
salary: 'Not Received',
class: ' Middle class',
fathersname: 'Murthy',
fathersOccupation: 'Business',
mothersname: 'Tamil teacher',
mothersOccupation: 'Government Teacher',
siblings: '1',
siblingsmarriage         : '0',
dhosam: 'No',
dhosamdetails: 'NA',
rasi: 'Magaram',
natchathiram: 'Avitam(2)',
Lagnam: 'thanusu',
Expectation: 'Doctor -- good family',

},

    ],
MTC16VeeduRemarriage: [
      {
        
                name: 'B Murali Krishnan',
        id: '32',
        dob: '24/10/1988',
        Gender:  'Male',
        Maritalstatus: 'Mutual divorce',
        dhosam:  'No',
        fathersname: 'Balasubramaniam',
        fathersOccupation: 'Business',
         mothersname: 'Jansi Rani',
        mothersOccupation: 'Home maker ',
        education: 'BCA',
        occupation: 'Business',
        company: 'Not Received',
        class: 'Upper',
        salary: 'Not Received',
        veedu : '16',
        siblings : ' 1 sister younger  un married ',
        native: 'Pollachi',
        livingLocation: 'Not Received',


      },
      

{id: '57',
name: 'Sidesh',
dob: '17.Nov.1989',
Gender: ' Male',
Maritalstatus: 'Remarrige',
educationdetail: 'Others',
education: ' Bsc',
Height: '5in',
Weight: '50 to 60  in KG',
BodyType: 'Average',
EatingHabits : 'Vegetarian',
native: 'salam  ',
livingLocation: 'artiam pati',
veedu: '8',
Thali : '(blank)',
Kulam : 'Not Recevied',
company: 'Not Recevied',
occupation: 'Not Recevied',
salary: ' 25,000 Rs',
class: 'Middle class ',
fathersname: 'vangadachalam ',
fathersOccupation: ' agricultural',
mothersname: ' vasantha',
mothersOccupation: ' house wife',
siblings: '3',
siblingsmarriage         : '2 (chennai)',
dhosam: '(Yes / No/Not sure)',
dhosamdetails: 'Not Received',
rasi: 'Not Recevied',
natchathiram: 'Not Recevied',
Lagnam: 'Not Recevied',
Expectation: 'No expectation',

},

    ],
MTC8VeeduRemarriage: [
      {
        
        id: '80',
        name: 'Hemalatha',
        dob: '31140',
        Gender: 'Female',
        Maritalstatus: 'Remarrige',
        educationdetail: 'Engineering /MBA',
        education: 'BE',
        Height: '5.4',
        Weight: '54',
        BodyType: ' Average',
        EatingHabits : 'Non Vegetarian',
        native: 'Krinakiri',
        livingLocation: 'tharmapuri',
        veedu: '8',
        Thali : 'Kombu',
        Kulam : 'Soppiyar ',
        company: 'CSC',
        occupation: 'Software engineer',
        salary: '75000',
        class: 'Upper middle class',
        fathersname: 'Kamala kannan(late)',
        fathersOccupation: 'NA',
        mothersname: 'Manonmani',
        mothersOccupation: ' house wife',
        siblings: '1',
        siblingsmarriage         : '1',
        dhosam: 'No',
        dhosamdetails: 'NA',
        rasi: 'Poosam',
        natchathiram: 'Kadakam',
        Lagnam: 'Kadakam',
        Expectation: 'IT , Good salary',
        
      },

      {
        id: '87',
        name: ' Saravanan Raja',
        dob: '7.3.1988',
        Gender: ' Male',
        Maritalstatus: ' Remarriage',
        educationdetail: 'BSC / BED / other',
        education: '12',
        Height: ' 6ft',
        Weight: ' 70 KG',
        BodyType: ' Average',
        EatingHabits : ' Non Vegetarian',
        native: ' CHENNAI',
        livingLocation: ' Bangalore',
        veedu: '8',
        Thali : 'Kombu',
        Kulam : ' Maaratiyar',
        company: 'Sai traders',
        occupation: 'Not Received',
        salary: ' 40 thousand',
        class: ' Upper Middle ',
        fathersname: 'Raja',
        fathersOccupation: ' Bussinees',
        mothersname: 'Lakshmi .R',
        mothersOccupation: 'Home Maker',
        siblings: '1',
        siblingsmarriage         : '1',
        dhosam: ' Yes',
        dhosamdetails: ' Ragu and Kethu ',
        rasi: ' Kumbham',
        natchathiram: ' AVITTAM',
        Lagnam: 'Kadagam',
        Expectation: ' 16Veedu Girl who is a good girl from a good family not any expections from girl house',
        
      },
      
    ],

    
  


  }

  data = this.dataSet.mainData;

  constructor() { }

  ngOnInit(): void {
  }

  optionChange(event) {
    this.data = this.dataSet[event.target.value];
  }

}
